### Site Settings ###
title        : "Vatsal Sejpal"
description  : >-
  Final-year Mathematics & Computing @ IIT Delhi
  ML Systems | Agents | Distributed Computing
baseurl      : ""                                # User site: must stay empty
repository   : "sejpalvatsal/sejpalvatsal.github.io"
remote_theme : "yousinix/portfolYOU"
open_new_tab : false                             # Set true if you want external links in new tabs


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                   # Safe to keep; you can drop docs later


### Author Info ###
author:
  name     : "Vatsal Sejpal"
  image    : "/assets/img/profile.jpg"
  email    : "sejpalvatsal152@gmail.com"
  github   : "sejpalvatsal"
  linkedin : "vatsal-sejpal-211759243"          # username/slug only, NOT full URL
  # Remove or fill others only if you actually use them:
  # twitter : ""
  # kaggle  : ""
  # etc.


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                     # For Documentation Only
    output: true                                # For Documentation Only


### Disqus ###
disqus:
  shortname:                                    # Leave empty unless you set it up


### Analytics ###
analytics:
  enabled: false
  google:
    tracking_id:                                # e.g. G-XXXXXXXXXX


### Buy me a coffee ###
buymeacoffee:
  enabled: false
  username:
  color: "#007bff"
  message: "Thank you for visiting."
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                     # For Documentation Only
      path: ""                                 # For Documentation Only
      type: "elements"                         # For Documentation Only
    values:                                    # For Documentation Only
      layout: "element"                        # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                          # Flip to true if you actually configure Disqus


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
